server:
  servlet:
    context-path: /boot

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://127.0.0.1:5432/xh

mybatis:
  mapper-locations: classpath:com/jus/**/*.xml

logging:
  level:
    com.jus: debug
#  config: classpath:logback.xml

